[package]
name = "math_and_algorithm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.3"
num-bigint = "0.4.6"
num-traits = "0.2.19"
bit-set = "0.8.0"